const UserDao = require("../models/UserDao");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");

/**
 * Registers a new user with the provided details.
 * @param {string} name - The full name of the user.
 * @param {string} openchatName - The Openchat username of the user.
 * @param {string} businessName - The business name of the user (optional).
 * @param {string} email - The email address of the user.
 * @param {string} password - The password for the user's account.
 * @param {string} phoneNumber - The phone number of the user (optional).
 * @param {number} cityId - The ID of the city where the user is located.
 * @param {string} role - The role of the user (e.g., "general" or "admin").
 * @param {Object} profileImage - The uploaded profile image file (optional).
 * @returns {Object} The newly created user object.
 * @throws Will throw an error if the registration fails.
 */
const registerUser = async (
  name,
  openchatName,
  businessName,
  email,
  password,
  phoneNumber,
  cityId,
  role,
  profileImage
) => {
  console.log("Input parameters to UserService.registerUser:", {
    name,
    openchatName,
    businessName,
    email,
    password,
    phoneNumber,
    cityId,
    role,
    profileImage,
  });
  // Regular expressions for input validation
  const emailReg =
    /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*\.[a-zA-Z]{2,3}$/;
  const pwReg = /(?=.*\d)(?=.*[a-zA-ZS]).{8,}/;
  const phoneReg = /^01([0|1|6|7|8|9])([0-9]{3,4})([0-9]{4})$/;

  // Validate name, email, password, and cityId
  if (
    !name ||
    !emailReg.test(email) ||
    !pwReg.test(password) ||
    !cityId ||
    !role
  ) {
    throw new Error("Invalid input format");
  }
  if (password.length < 8) {
    throw new Error("Password too short");
  }

  // Validate phone number if provided
  if (phoneNumber && !phoneReg.test(phoneNumber)) {
    throw new Error("Invalid phone number");
  }

  // Check if the user already exists
  const existingUser = await UserDao.getUserByEmail(email);
  if (existingUser) {
    throw new Error("User already exists");
  }

  // Hash the password
  const hashedPassword = bcrypt.hashSync(password, bcrypt.genSaltSync());

  const profileImagePath = profileImage
    ? `/uploads/profile_pictures/${profileImage.filename}`
    : null;

  try {
    const newUser = await UserDao.createUser(
      name,
      openchatName,
      businessName,
      email,
      hashedPassword,
      phoneNumber,
      cityId,
      role,
      profileImagePath
    );
    console.log("New user created by UserService.registerUser:", newUser);
    return newUser;
  } catch (error) {
    console.log("Error in UserService.registerUser:", error);
    throw error;
  }
};

/**
 * Authenticates a user using their email and password.
 * @param {string} email - The email of the user trying to authenticate.
 * @param {string} password - The password of the user for authentication.
 * @returns {Object} The authenticated user object and a JWT token.
 * @throws Will throw an error if authentication fails.
 * @throws Will throw an error if required fields are missing.
 */
const authenticateUser = async (email, password) => {
  console.log("Input parameters to UserService.authenticateUser:", {
    email,
    password,
  });
  // Validate input
  if (!email || !password) {
    throw new Error("Missing required fields");
  }

  const user = await UserDao.getUserByEmail(email);
  console.log("User found by UserService.authenticateUser:", user);
  if (!user || !(await bcrypt.compare(password, user.password))) {
    throw new Error("Invalid email or password");
  }

  // Generate a JWT token
  try {
    const token = jwt.sign({ id: user.id }, process.env.JWT_SECRET_KEY, {
      expiresIn: "24h",
    });
    console.log("Token generated by UserService.authenticateUser:", token);
    return { user, token };
  } catch (error) {
    console.log(
      "Error generating token in UserService.authenticateUser:",
      error
    );
    console.error("Error generating token:", error);
    throw new Error("Failed to generate token: " + error.message);
  }
};

/**
 * Updates a user's profile image.
 * @param {number} userId - The ID of the user to update.
 * @param {Object} profileImage - The uploaded profile image file.
 * @returns {Object} The updated user profile.
 * @throws Will throw an error if the update operation fails or user is not found.
 */
const updateUserProfileImage = async (userId, profileImage) => {
  console.log("Input parameters to UserService.updateUserProfileImage:", {
    userId,
    profileImage,
  });

  // Validate input
  if (!userId || !profileImage) {
    throw new Error("Missing required fields");
  }

  const profileImagePath = `/uploads/profile_pictures/${profileImage.filename}`;

  try {
    const updatedUser = await UserDao.updateUserProfile(userId, {
      profile_image: profileImagePath,
    });
    return updatedUser;
  } catch (error) {
    console.log("Error updating user profile image:", error);
    console.error("Error updating user profile image:", error);
    throw new Error("Failed to update profile image");
  }
};

/**
 * Retrieves all user profiles.
 * @returns {Array} An array of user objects.
 * @throws Will throw an error if the database operation fails.
 * @throws Will throw an error if no users are found.
 */
const getAllUsers = async () => {
  try {
    const users = await UserDao.getAllUsers();
    return users;
  } catch (error) {
    console.error("Error getting all users:", error);
    throw new Error("Failed to get all users");
  }
};

/**
 * Retrieves a user's profile information by their ID.
 * @param {number} userId - The ID of the user to retrieve.
 * @returns {Object} The user's profile information.
 * @throws Will throw an error if the user is not found or the database operation fails.
 * @throws Will throw an error if required fields are missing.
 */
const getUserProfile = async (userId) => {
  console.log("Input parameters to UserService.getUserProfile:", { userId });
  // Validate input
  if (!userId) {
    throw new Error("Missing required fields");
  }

  try {
    const user = await UserDao.getUserById(userId);
    // console.log("User profile fetched by UserService.getUserProfile:", user);
    return user;
  } catch (error) {
    console.log("Error retrieving user profile:", error);
    console.error("Error retrieving user profile:", error);
    throw new Error("Failed to get user profile");
  }
};

/**
 * Retrieves a user's preferences by their ID.
 * @param {number} userId - The ID of the user to retrieve preferences for.
 * @returns {Object} The user's preferences.
 * @throws Will throw an error if the user is not found or the database operation fails.
 * @throws Will throw an error if required fields are missing.
 */
const getUserPreferences = async (userId) => {
  console.log("Input parameters to UserService.getUserPreferences:", {
    userId,
  });
  // Validate input
  if (!userId) {
    throw new Error("Missing required fields");
  }

  try {
    const preferences = await UserDao.getUserPreferences(userId);
    return preferences;
  } catch (error) {
    console.log("Error retrieving user preferences:", error);
    console.error("Error retrieving user preferences:", error);
    throw new Error("Failed to get user preferences");
  }
};

/**
 * Updates a user's profile information.
 * @param {number} userId - The ID of the user to update.
 * @param {Object} profileData - The updated profile information.
 * @returns {Object} The updated user profile.
 * @throws Will throw an error if the user is not found or the database operation fails.
 * @throws Will throw an error if required fields are missing.
 */
const updateUserProfile = async (userId, profileData) => {
  console.log("Input parameters to UserService.updateUserProfile:", {
    userId,
    profileData,
  });
  // Validate input
  if (!userId || !profileData) {
    throw new Error("Missing required fields");
  }

  try {
    const updatedUser = await UserDao.updateUserProfile(userId, profileData);
    return updatedUser;
  } catch (error) {
    console.log("Error updating user profile:", error);
    console.error("Error updating user profile:", error);
    throw new Error("Failed to update user profile");
  }
};

/**
 * Updates a user's location in the database.
 * @param {number} userId - The ID of the user to update.
 * @param {number} cityId - The ID of the city to update the user's location to.
 * @returns {Object} The updated user object.
 * @throws Will throw an error if the user is not found or the database operation fails.
 * @throws Will throw an error if the city is not found.
 */
const updateUserLocation = async (userId, cityId) => {
  console.log("Input parameters to UserService.updateUserLocation:", {
    userId,
    cityId,
  });
  // Validate input
  if (!userId || !cityId) {
    throw new Error("Missing required fields");
  }

  try {
    const updatedUser = await UserDao.updateUserLocation(userId, cityId);
    return updatedUser;
  } catch (error) {
    console.log("Error updating user location:", error);
    console.error("Error updating user location:", error);
    throw new Error("Failed to update user location");
  }
};

// /**
//  * Updates a user's role in the database.
//  * @param {number} userId - The ID of the user to update.
//  * @param {string} newRole - The new role for the user.
//  * @returns {Object} The updated user object.
//  * @throws Will throw an error if the user is not found or the database operation fails.
//  * @throws Will throw an error if required fields are missing.
//  */
// const updateUserRole = async (userId, newRole) => {
//   try {
//     const updatedUser = await UserDao.updateUserRole(userId, newRole);
//     if (!updatedUser) {
//       throw new Error("User not found or unable to update");
//     }
//     return updatedUser;
//   } catch (error) {
//     console.error("Error updating user role:", error);
//     throw new Error("Failed to update user role");
//   }
// };

/**
 * Updates a user's preferences in the database.
 * @param {number} userId - The ID of the user to update.
 * @param {Array} minorCategoryIds - An array of minor category IDs for the user's preferences.
 * @returns {Array} The updated user preferences.
 * @throws Will throw an error if the user is not found or the database operation fails.
 * @throws Will throw an error if required fields are missing.
 */
const updateUserPreferences = async (userId, minorCategoryIds) => {
  console.log("Input parameters to UserService.updateUserPreferences:", {
    userId,
    minorCategoryIds,
  });
  // Validate input
  if (!userId || !minorCategoryIds) {
    throw new Error("Missing required fields");
  }

  try {
    const updatedPreferences = await UserDao.updateUserPreferences(
      userId,
      minorCategoryIds
    );
    return updatedPreferences;
  } catch (error) {
    console.log("Error updating user preferences:", error);
    console.error("Error updating user preferences:", error);
    throw new Error("Failed to update user preferences");
  }
};

/**
 * Soft deletes a user from the database.
 * @param {number} userId - The ID of the user to soft delete.
 * @returns {Object} The deleted user object.
 * @throws Will throw an error if the user is not found or the database operation fails.
 */
const softDeleteUser = async (userId) => {
  console.log("Input parameters to UserService.softDeleteUser:", { userId });
  // Validate input
  if (!userId) {
    throw new Error("Missing required fields");
  }

  try {
    const result = await UserDao.softDeleteUser(userId);
    return result;
  } catch (error) {
    console.log("Error soft deleting user:", error);
    console.error("Error soft deleting user:", error);
    throw new Error("Failed to soft delete user");
  }
};

// Export the service functions to be used by other parts of the application
module.exports = {
  registerUser,
  authenticateUser,
  updateUserProfileImage,
  updateUserProfile,
  updateUserLocation,
  updateUserPreferences,
  getAllUsers,
  getUserProfile,
  getUserPreferences,
  softDeleteUser,
  // updateUserRole,
};
